//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMMaintenanceJobEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class frmMain
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmMain()
        {
            InitializeComponent();
            this.a();
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMMaintenanceJobEditor.frmMain", typeof(frmMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Changes to the Create Audit Partition next run date may have unintended consequences. Do not change this date unless it is absolutely necessary. It is recommended that you change the future schedule instead of the next job instance.Are you sure that you want to change this date and time?.
        /// </summary>
        internal static string AuditWarning1 {
            get {
                return ResourceManager.GetString("AuditWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Changes to this date may have unintended consequences.                You have indicated you want to change the date time which is not recommended.
        ///If you change the date/time you may press the Refresh button to clear the changes but this must be done prior to pressing the Update button.             Are you absolutely sure you want to continue?.
        /// </summary>
        internal static string AuditWarning2 {
            get {
                return ResourceManager.GetString("AuditWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Cleared....
        /// </summary>
        internal static string ChangesCleared {
            get {
                return ResourceManager.GetString("ChangesCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception was caught, the application will now be shut down.
        /// </summary>
        internal static string ExceptionAndAppShutdown {
            get {
                return ResourceManager.GetString("ExceptionAndAppShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This assembly must be run from the:
        ///{0}\\ directory.
        ///
        ///The current location is: {1}\\.
        /// </summary>
        internal static string ExceptionAssemblyLocation {
            get {
                return ResourceManager.GetString("ExceptionAssemblyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This build has expired.  Please contact the developer for a new build or visit.
        /// </summary>
        internal static string ExceptionBuildExpired {
            get {
                return ResourceManager.GetString("ExceptionBuildExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be more exactly two parts to a recurrence pattern.
        /// </summary>
        internal static string ExceptionRecurrenceError {
            get {
                return ResourceManager.GetString("ExceptionRecurrenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence Pattern is invalid.
        /// </summary>
        internal static string ExceptionRecurrencePattern {
            get {
                return ResourceManager.GetString("ExceptionRecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For MUI Updates.
        /// </summary>
        internal static string jobNameCheckforLanguageUpdates {
            get {
                return ResourceManager.GetString("jobNameCheckforLanguageUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check FullText ColumnStatus.
        /// </summary>
        internal static string jobNameCheckFullTextIndexColumnStatusOperation {
            get {
                return ResourceManager.GetString("jobNameCheckFullTextIndexColumnStatusOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Inactive Workflow Assemblies.
        /// </summary>
        internal static string jobNameCleanupWorkflows {
            get {
                return ResourceManager.GetString("jobNameCleanupWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Audit Partition.
        /// </summary>
        internal static string jobNameCreateAuditPartition {
            get {
                return ResourceManager.GetString("jobNameCreateAuditPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Service.
        /// </summary>
        internal static string jobNameDeletionService {
            get {
                return ResourceManager.GetString("jobNameDeletionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing Management.
        /// </summary>
        internal static string jobNameIndexManagement {
            get {
                return ResourceManager.GetString("jobNameIndexManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Sharing Counts.
        /// </summary>
        internal static string jobNameRefreshReadSharingSnapshots {
            get {
                return ResourceManager.GetString("jobNameRefreshReadSharingSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Entity Row Counts.
        /// </summary>
        internal static string jobNameRefreshRowCountSnapshots {
            get {
                return ResourceManager.GetString("jobNameRefreshRowCountSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindex All.
        /// </summary>
        internal static string jobNameReindexAll {
            get {
                return ResourceManager.GetString("jobNameReindexAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has not been run.
        /// </summary>
        internal static string JobNotRun {
            get {
                return ResourceManager.GetString("JobNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREQ=DAILY;INTERVAL=30;.
        /// </summary>
        internal static string OverrideSchedule {
            get {
                return ResourceManager.GetString("OverrideSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Maintenance Job Editor.
        /// </summary>
        internal static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://crmjobeditor.codeplex.com/.
        /// </summary>
        internal static string ProjectUrl {
            get {
                return ResourceManager.GetString("ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string sDays {
            get {
                return ResourceManager.GetString("sDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string sHours {
            get {
                return ResourceManager.GetString("sHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string sMinutes {
            get {
                return ResourceManager.GetString("sMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string sMonths {
            get {
                return ResourceManager.GetString("sMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string StatusCheckVersion {
            get {
                return ResourceManager.GetString("StatusCheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Completed.
        /// </summary>
        internal static string StatusUpdateCompleted {
            get {
                return ResourceManager.GetString("StatusUpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed with error:.
        /// </summary>
        internal static string StatusUpdateFailed {
            get {
                return ResourceManager.GetString("StatusUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleGroupOrganizationMaintenanceJobs.
        /// </summary>
        internal static string tblScaleGrp {
            get {
                return ResourceManager.GetString("tblScaleGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this box is checked all current and future job changes will be applied
        ///to ALL jobs in the currently selected organization..
        /// </summary>
        internal static string ToolTipchkAllJobs {
            get {
                return ResourceManager.GetString("ToolTipchkAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time indicating the next time the job will run.
        ///To run the job immediatley, set this date/time to a date in the past.
        ///The Asynchronus Service must be running for the job to run..
        /// </summary>
        internal static string ToolTipdtNextRun {
            get {
                return ResourceManager.GetString("ToolTipdtNextRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time used to calculate the next time a job runs.
        ///This setting will only be used the next time the async service runs this particular job.
        ///
        ///For Instance:
        ///If the base time is set to 1:00AM and the interval is every 1 day, the next runtime
        ///generated will be 1:00AM of the current date plus the jobs interval of 1 day.
        ///The final setting for job next run would be 1:00AM of the next day..
        /// </summary>
        internal static string ToolTipdtRecStartTime {
            get {
                return ResourceManager.GetString("ToolTipdtRecStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job type will only allow you to change the time,
        ///any date value will be ignored for this job type..
        /// </summary>
        internal static string ToolTipTimeOnly {
            get {
                return ResourceManager.GetString("ToolTipTimeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to check for a newer version newer than:.
        /// </summary>
        internal static string ToolTipTssLink {
            get {
                return ResourceManager.GetString("ToolTipTssLink", resourceCulture);
            }
        }
    }
}
